name = 'NYA10 HUGO THEME'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'SIMPLE KAWAII THEME'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/nullnyat/nya10-hugotheme'

# If you have a running demo of the theme
demosite = 'https://nya10-hugotheme-demo.nca10.moe'

# Taxonomy terms
tags = ['blog', "personal"]
features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'nullnyat', homepage = 'nullnyat.nca10.moe'}
]

# If the theme has a single author
[author]
  name = 'nullnyat'
  homepage = 'nullnyat.nca10.moe'

# If porting an existing theme
[original]
  author = 'nullnyat'
  homepage = 'nullnyat.nca10.moe'
  repo = 'https://github.com/nullnyat/nya10-hugotheme'
